# Motion control configuration
motion:
  # Movement limits
  max_linear_velocity: 1.5       # Maximum linear velocity in m/s
  max_angular_velocity: 2.0      # Maximum angular velocity in rad/s
  max_acceleration: 2.0          # Maximum acceleration in m/s²
  
  # Control parameters
  position_tolerance: 0.05       # Position tolerance in meters
  orientation_tolerance: 0.1     # Orientation tolerance in radians
  
  # Gait settings
  default_gait: "trot"           # Default gait type
  step_height: 0.1               # Default step height in meters
  
# Joint control settings
joints:
  # Joint limits (in radians)
  hip_min: -0.8
  hip_max: 0.8
  thigh_min: -3.0
  thigh_max: 3.0
  calf_min: -2.7
  calf_max: -0.5
  
  # Control gains
  kp: 20.0                       # Proportional gain
  kd: 0.5                        # Derivative gain
  
# Stability control
stability:
  enable_auto_balance: true      # Enable automatic balance correction
  balance_threshold: 0.2         # Balance threshold in radians
  recovery_time: 2.0             # Recovery time in seconds
